### ISSUE TITLE
socket example

### ISSUE THREAD

**Issue by denisdemais** [oberhofer/luacwrap#1]
Hi,
you software are IMPRESSIVE!!!

do you can make a socket() like example using yours lib?

**Comment by oberhofer** [comment]
Thanks. Although luacwrap can be used to wrap the socket API or WinSock2 API I have no plans to do this (so far). I suggest you use luasocket (https://github.com/diegonehab/luasocket) which has everything I needed so far to deal with sockets from Lua.
